server:
  port: 8080

spring:
  application:
    name: hrtms-be

  datasource:
    # Nhớ thay đổi tên database, username và password cho khớp với máy cậu nhé
    url: jdbc:sqlserver://localhost:1433;databaseName=HRTMS;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

app:
  jwt:
    secret: "YourSuperSecretKeyForJWTGenerationHRTMSProject2026"
    expiration: 86400000 # 1 day in milliseconds
  otp:
    mock: true # set to false to send real emails
