package com.swp.hrtms.hrtmsbe.enums;

public enum NotificationType {
    DONE, VERIFI_CERTIFICATE, ACCEPT_CERTIFICATE, REJECT_CERTIFICATE, REFEREE_ACCEPTED, REFEREE_REJECTED,
    REGISTRATION_VERIFY, DOCTOR_ACCEPTED, DOCTOR_REJECTED, NEW_TOURNAMENT, TOURNAMENT_UPDATE, TOURNAMENT_CANCELLED,
    NEW_RACE, RACE_UPDATE, RACE_CANCELLED, REGISTRATION_APPROVED, REGISTRATION_REJECTED, INVITATION_ACCEPTED,
    INVITATION_REJECTED, SYSTEM, REFEREE_INVITATION
}
